### ISSUE TITLE
Publish to NuGet fails

### ISSUE THREAD

**Issue by BrightSoul** [serilog-contrib/serilog-sinks-slack#39]
Hi guys, thanks for merging my last pull request! The new version wasn't published to NuGet, unfortunately, due to this error.
```
😭 error: Response status code does not indicate success: 403
(The specified API key is invalid, has expired, or does not have permission to access the specified package.).
```

Would you please check it? You can see the full log here:
https://github.com/serilog-contrib/serilog-sinks-slack/runs/5202446259?check_suite_focus=true

Thanks!
Moreno

**Comment by TrapperHell** [comment]
Hi,

I have already brought this to the attention of the other maintainers, however I don't have access to the NuGet account responsible for the builds. Hopefully we'll have this sorted out soon.

**Comment by BrightSoul** [comment]
Thank you @mgibas!
Would you please manually re-run the last failed build? Hopefully it will succeed now.
https://github.com/serilog-contrib/serilog-sinks-slack/actions/runs/1847786204

Moreno

**Comment by TrapperHell** [comment]
Seems like 2.1.0 is out. The build still failed actually (the NuGet PUT response didn't include the package version strangely), but we should be [live](https://www.nuget.org/packages/Serilog.Sinks.Slack/2.1.0).

Will wait for a bit to ensure that all is well and close the issue.

**Comment by BrightSoul** [comment]
@TrapperHell, yes, I can indeed reference the new package version.
All is in working order, thanks for your support!
