### ISSUE TITLE
Sink not working in .NET Framework 4.5.2

### ISSUE THREAD

**Issue by TrapperHell** [serilog-contrib/serilog-sinks-slack#40]
Based on a reproducible report by @GFoley83 in issue #23 . The following code should work (and does on .NET Core) but does not when targetting .NET Framework 4.5.2

```
var config = new LoggerConfiguration().WriteTo.Slack("https://hooks.slack.com/services/XXX");
Log.Logger = config.CreateLogger();

Log.Logger.Information("Hello world");
Log.CloseAndFlush();
```

**Comment by GFoley83** [comment]
@TrapperHell  I can confirm that v.2.2.1 works as expected with .NET Frameworks v4.5.2. Thanks for your help!
